/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.AuthService;
import ticket.booking.services.TrainService;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {


    public static void main(String[] args) {
        System.out.println("Running Train Booking System");

        Scanner scanner = new Scanner(System.in);
        AuthService authService;
        TrainService trainService;

        // AuthService loads users.json on startup — if this fails, app cannot run
        try{
            authService = new AuthService();
        }catch (IOException ex){
            System.out.println("Failed to load user data. Exiting...");
            return;
        }
        try{
            trainService = new TrainService();
        } catch (IOException e) {
            System.out.println("Failed to load train data. Exiting...");
            return;
        }

        User loggedInUser = null;


        int option = 0;
        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
//            System.out.println("3. Fetch Bookings");
            System.out.println("3. Search Trains");
//            System.out.println("5. Book a Seat");
//            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();

            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String signUpName = scanner.next();
                    System.out.println("Enter the password to signup");
                    String signUpPassword = scanner.next();
                    authService.signUp(signUpName, signUpPassword);
                    break;

                case 2:
                    System.out.println("Enter the username to login:");
                    String loginName = scanner.next();
                    System.out.println("Enter the password");
                    String loginPassword = scanner.next();
                    Optional<User> result = authService.login(loginName, loginPassword);

                    if(result.isPresent()){
                        loggedInUser = result.get();
                        System.out.println("Welcome, " + loggedInUser.getName() + "!");
                    }else {
                        System.out.println("Invalid credentials.");
                    }
                    break;

                case 3:
                    System.out.println("Enter your source station");
                    String sourceStation = scanner.next();
                    System.out.println("Enter your destination station");
                    String destinationStation = scanner.next();

                    List<Train> trainsResult = trainService.searchTrains(sourceStation, destinationStation);

                    if(trainsResult.isEmpty()){
                        System.out.println("No trains found. Please search a different route");
                    }
                    else{
                        System.out.printf("%d trains are found%n", trainsResult.size());
                        for (int i = 0; i < trainsResult.size(); i++) {
                            System.out.println((i + 1) + ". Train ID: " + trainsResult.get(i).getTrainId() + "(" + trainsResult.get(i).getTrainNo() + ")" + " | Stations: " + String.join(" -> ", trainsResult.get(i).getStations()));
                        }
                    }
                    break;
            }
        }
    }
}
